### ISSUE TITLE
ColorScheme and dark doesn't work in the browser

### ISSUE THREAD

**Issue by shashank1010** [remcohaszing/rehype-mermaid#13] opened 2024-03-28 14:35 UTC
First off, Thank you for creating this useful library.

I have a very simple setup.
```
     const file = await unified()
                    .use(remarkParse)
                    .use(remarkGfm)
                    .use(remarkRehype)
                    .use(rehypeMermaid, {
                        colorScheme,
                        dark: colorScheme === 'dark' || undefined,
                    })
                    .use(rehypeReact, rehypeReactOptions)
                    .process(markdown);
```

When I pass colorScheme as dark and dark: true, it doesn't matter.
The output is always exactly the same.

Upon investigating, I found that the options are not passed down to mermaid.render and thus, the result always is in light mode.
<img width="475" alt="image" src="https://github.com/remcohaszing/rehype-mermaid/assets/3106368/e24cd7a5-e98b-420c-8cb1-54334ae291b4">

I was surprised that no one ever faced this issue.
I suppose my only next option is to create a dark mode css theme of my own.

**Comment by remcohaszing** [comment] 2024-03-29 10:24
I’m glad you like it. :)

The problem is that `mermaid.render()` doesn’t accept a theme, `mermaid.initialize()` does, but this configures it in global state. I don’t want this library to touch global state.

I think your best options is to have something like this in your code base:

```js
import mermaid from 'mermaid'


const themeMatcher = window.matchMedia('(prefers-color-scheme: dark)')
themeMatcher.onchange = configureMermaid

function configureMermaid() {
  mermaid.initialize({
    startOnLoad: true,
    theme: themeMatcher.matches ? 'dark' : 'default'
  })
}
```

Then use the [`pre-mermaid`](https://github.com/remcohaszing/rehype-mermaid#pre-mermaid) strategy.

I would absolutely love to support this though. It would be great if you could realize support for passing a theme to `mermaid.render()`, so I can support it here. For now I’m closing this issue, as it’s not actionable for me.

**Closed by remcohaszing** 2024-03-29 10:24 UTC
